prompt_eval ="""You are an expert document analyst.
Read the provided document pages and any accompanying figures or images.

Produce a clear, factual, and concise summary that accurately conveys the document’s purpose, key facts, findings, and conclusions.

Guidelines:
1. Focus on the document’s core content — main ideas, results, and implications.
2. If the document includes visuals (charts, tables, or attachments), briefly summarize their insights (e.g., key data, trends, or comparisons).
3. Write in your own words — do not copy sentences.
4. Exclude introductory phrases like “This document describes…” or “Here’s a summary…” or "Here is a concise summary of the document…".
5. Avoid opinions or unnecessary details.
6. Aim for 3–5 sentences, or fewer if the content is short.

Now summarize the document precisely and cohesively."""


prompt_eval_pro = """You are an expert government report analyst.
Your task is to read the provided document pages and their accompanying figures or images,
and produce a comprehensive Executive Summary.

Follow these strict guidelines to ensure high quality:
1. **Scope:** Cover all major sections of the report, including the background, methodology, key findings, and specific recommendations. Do not skip the conclusion.
2. **Detail Level:** Be detailed and comprehensive. Do not over-summarize. Include specific numbers, dates, statute names, and agency names found in the text and tables.
3. **Visuals:** Integrate insights from charts and tables into the narrative where relevant (e.g., "As shown in Figure 1...").
4. **Style:** Use a formal, objective, and professional tone matching a government executive summary.
5. **Structure:** Organize the summary logically with clear paragraphs.
6. **Length:** The summary should be extensive enough to cover all critical information. Do NOT restrict yourself to a short length; aim for a detailed overview (typically 500+ words).

Now, generate the Executive Summary."""



prompt_images = """Describe the content of the image in detail.
For context,the image is part of a research paper explaining the transformers
architecture. Be specific about graphs, such as bar plots."""

prompt_tables = """
Analyze this image of a table from a research paper.
1. Transcribe the data into a Markdown table format, preserving all column headers and row labels exactly.
2. Provide a concise summary of the key results. Highlight the best-performing models (often bolded numbers) and identify any significant trends or comparisons being made.
"""

prompt_text = """You are an assistant tasked with summarizing tables and text.
Give a concise summary of the table or text.

Respond only with the summary, no additionnal comment.
Do not start your message by saying "Here is a summary" or anything like that.
Just give the summary as it is.

Table or text chunk: {element}"""

SUMMARY_PROMPT = """\
# Instruction
You are an expert evaluator. Your task is to evaluate the quality of the responses generated by AI models.
We will provide you with the user input and an AI-generated responses.
You should first read the user input carefully for analyzing the task, and then evaluate the quality of the responses based on the Criteria provided in the Evaluation section below.
You will assign the response a rating following the Rating Rubric and Evaluation Steps. Give step-by-step explanations for your rating, and only choose ratings from the Rating Rubric.

# Evaluation
## Metric Definition
You will be assessing summarization quality, which measures the overall ability to summarize text. Pay special attention to length constraints, such as in X words or in Y sentences. The instruction for performing a summarization task and the context to be summarized are provided in the user prompt. The response should be shorter than the text in the context. The response should not contain information that is not present in the context.

## Criteria
Instruction following: The response demonstrates a clear understanding of the summarization task instructions, satisfying all of the instruction's requirements.
Groundedness: The response contains information included only in the context. The response does not reference any outside information.
Conciseness: The response summarizes the relevant details in the original text without a significant loss in key information without being too verbose or terse.
Fluency: The response is well-organized and easy to read.

## Rating Rubric
5: (Very good). The summary follows instructions, is grounded, is concise, and fluent.
4: (Good). The summary follows instructions, is grounded, concise, and fluent.
3: (Ok). The summary mostly follows instructions, is grounded, but is not very concise and is not fluent.
2: (Bad). The summary is grounded, but does not follow the instructions.
1: (Very bad). The summary is not grounded.

## Evaluation Steps
STEP 1: Assess the response in aspects of instruction following, groundedness, conciseness, and verbosity according to the criteria.
STEP 2: Score based on the rubric.

# User Inputs and AI-generated Response
## User Inputs

### Prompt
{prompt}

## AI-generated Response
{response}
"""

prompt_get_num = """Return only the numerical value of the evaluation."""

COMPARISON_PROMPT = """
You are an expert evaluator. Your task is to compare a 'Prediction' summary against a 'Reference' (gold-standard) summary.

Reference Summary:
---
{reference}
---

Prediction Summary:
---
{prediction}
---

## Evaluation Steps:
1.  **Assess Groundedness:** Is the 'Prediction' factually supported by the 'Reference'? If it contains information *not* in the reference, it is "Not Grounded."
2.  **Assess Instruction Following:** Does the 'Prediction' summarize the *substance* and main ideas of the 'Reference'?
3.  **Assess Conciseness & Fluency:** Is the 'Prediction' concise and well-written?

## Final Score Rubric:
Please provide a single numerical rating from 1 to 5 based *only* on the following rubric:

**5 (Very good):** The summary perfectly follows all instructions. It is fully grounded, captures all main ideas, is concise, and is fluent.
**4 (Good):** The summary follows instructions and is grounded. It might have minor issues, like missing one secondary point or being slightly wordy, but is otherwise a good summary.
**3 (Ok):** The summary is grounded, but has significant issues. It might miss key ideas, or be not concise and not fluent.
**2 (Bad):** The summary is grounded, but does not follow the main instruction (e.g., it summarizes the wrong content, like the document's form instead of its substance).
**1 (Very bad):** The summary is not grounded (it contains hallucinations or information not present in the reference).

## Your Task:
First, provide a brief, one-paragraph analysis of your reasoning.
Second, provide the final score as a numerical rating ranging from 1 to 5.
"""

COMBINED_EVAL_PROMPT = """
You are an expert evaluator. Your task is to assess a 'Prediction Summary' from an AI model.
You will evaluate it on two criteria and provide a final JSON response.

---
[Original Prompt Given to AI]
{prompt}
---
[Reference (Gold-Standard) Summary]
{reference}
---
[Prediction Summary to Evaluate]
{prediction}
---

## TASK 1: Quality Evaluation
Evaluate the 'Prediction Summary' against the 'Original Prompt' using this rubric:
5 (Very good): Follows instructions, grounded, concise, fluent.
4 (Good): Follows instructions, grounded, minor issues.
3 (Ok): Mostly follows instructions, grounded, but not concise/fluent.
2 (Bad): Grounded, but fails the main instruction (e.g., wrong topic).
1 (Very bad): Not grounded (hallucination).

## TASK 2: Comparison Evaluation
Evaluate the 'Prediction Summary' against the 'Reference Summary' using this rubric:
5 (Very good): Perfectly captures all main ideas, fully grounded.
4 (Good): Captures main ideas, grounded, minor points missing.
3 (Ok): Grounded, but misses key ideas.
2 (Bad): Grounded, but summarizes the wrong content.
1. (Very bad): Not grounded in the reference.

## Your Task:
Provide *only* a single, valid JSON object matching the requested schema. Do not add any other text or analysis.
"""